
export const INGREDIENT_LIST: string[] = [
  "Salt",
  "Black Pepper",
  "Olive Oil",
  "Garlic",
  "Onion",
  "Butter",
  "Flour",
  "Sugar",
  "Eggs",
  "Milk",
  "Water",
  "Chicken Breast",
  "Ground Beef",
  "Rice",
  "Pasta",
  "Tomatoes",
  "Potatoes",
  "Carrots",
  "Celery",
  "Lemon",
  "Lime",
  "Cilantro",
  "Parsley",
  "Basil",
  "Oregano",
  "Thyme",
  "Rosemary",
  "Paprika",
  "Cumin",
  "Chili Powder",
  "Cayenne Pepper",
  "Soy Sauce",
  "Worcestershire Sauce",
  "Honey",
  "Maple Syrup",
  "Mustard (Dijon)",
  "Mayonnaise",
  "Ketchup",
  "Vinegar (White)",
  "Vinegar (Apple Cider)",
  "Vinegar (Balsamic)",
  "Red Wine",
  "White Wine",
  "Chicken Broth",
  "Beef Broth",
  "Vegetable Broth",
  "Heavy Cream",
  "Sour Cream",
  "Yogurt (Plain)",
  "Cheese (Cheddar)",
  "Cheese (Mozzarella)",
  "Cheese (Parmesan)",
  "Cheese (Feta)",
  "Cheese (Goat)",
  "Bacon",
  "Sausage",
  "Shrimp",
  "Salmon",
  "Tuna (canned)",
  "Bread",
  "Tortillas (Flour)",
  "Tortillas (Corn)",
  "Beans (Black)",
  "Beans (Kidney)",
  "Beans (Pinto)",
  "Chickpeas (Garbanzo Beans)",
  "Lentils",
  "Corn (canned or frozen)",
  "Peas (frozen)",
  "Spinach",
  "Kale",
  "Lettuce (Romaine)",
  "Cucumber",
  "Bell Pepper (Green)",
  "Bell Pepper (Red)",
  "Bell Pepper (Yellow)",
  "Jalapeño",
  "Mushrooms",
  "Zucchini",
  "Eggplant",
  "Broccoli",
  "Cauliflower",
  "Asparagus",
  "Green Beans",
  "Avocado",
  "Ginger",
  "Scallions (Green Onions)",
  "Almonds",
  "Walnuts",
  "Peanuts",
  "Cashews",
  "Sesame Oil",
  "Sesame Seeds",
  "Cinnamon",
  "Nutmeg",
  "Cloves",
  "Vanilla Extract",
  "Baking Soda",
  "Baking Powder",
  "Cornstarch",
  "Cocoa Powder",
  "Chocolate Chips",
  "Oats (Rolled)",
  "Quinoa",
  "Couscous",
  "Tofu",
  "Tempeh",
  "Edamame",
  "Capers",
  "Olives (Kalamata)",
  "Sun-dried Tomatoes",
  "Artichoke Hearts",
  "Pineapple",
  "Mango",
  "Berries (Mixed)",
  "Apples",
  "Bananas",
  "Oranges",
  "Grapes",
  "Coconut Milk",
  "Fish Sauce",
  "Sriracha",
  "Hoisin Sauce",
  "Miso Paste",
  "Panko Breadcrumbs",
  "Mustard (Yellow)",
  "Pickles",
  "Relish",
  "Hot Sauce",
  "Barbecue Sauce",
  "Ranch Dressing",
  "Italian Dressing",
  "Tahini",
  "Hummus",
  "Pita Bread",
  "Naan Bread",
  "Bay Leaves",
  "Coriander (ground)",
  "Turmeric",
  "Cardamom",
  "Garam Masala",
  "Curry Powder",
  "Fennel Seeds",
  "Star Anise",
  "Dill",
  "Mint",
  "Chives",
  "Leeks",
  "Shallots",
  "Radishes",
  "Beets",
  "Sweet Potatoes",
  "Butternut Squash",
  "Acorn Squash",
  "Spaghetti Squash",
  "Cabbage",
  "Bok Choy",
  "Arugula",
  "Endive",
  "Pears",
  "Peaches",
  "Plums",
  "Cherries",
  "Watermelon",
  "Cantaloupe",
  "Honeydew Melon",
  "Pomegranate Seeds",
  "Dates",
  "Figs",
  "Raisins",
  "Cranberries (dried)",
  "Pecans",
  "Pistachios",
  "Macadamia Nuts",
  "Sunflower Seeds",
  "Pumpkin Seeds",
  "Flax Seeds",
  "Chia Seeds",
  "Agave Nectar",
  "Brown Sugar",
  "Powdered Sugar",
  "Molasses",
  "Yeast",
  "Gelatin",
  "Canola Oil",
  "Vegetable Oil",
  "Coconut Oil",
  "Peanut Oil",
  "Grapeseed Oil",
  "Avocado Oil",
  "Cream Cheese",
  "Cottage Cheese",
  "Ricotta Cheese",
  "Blue Cheese",
  "Gouda",
  "Provolone",
  "Swiss Cheese",
  "Half-and-Half",
  "Buttermilk",
  "Evaporated Milk",
  "Condensed Milk",
  "Ground Turkey",
  "Ground Pork",
  "Lamb",
  "Cod",
  "Tilapia",
  "Scallops",
  "Mussels",
  "Clams",
  "Crab",
  "Lobster"
];
